---
title: "L08 · Fitting data with function -- the exact approach"
subtitle: "How to connect exact data points using numerical methods?"
body-classes: lecture-page
---

## The question

**When we have only a few data points, how can we create function to know the values in between the data points?**

## Learning outcomes

<fix me, LLM writes>

Lecture 8

Hope you have enjoyed last weeks lecture so far. We now know that from a physical law (Gibbs free energy) we are able to determine 1) what is the possible volume in a state 2) what are the most stable phase. They are very useful for mat science applications. My question is whether you could make it something truly as a phase diagram

<for this part we don;t need a detailed results, just a diagram>

:9’frlm last lecture given one Gibbs curve I would minimize and get 2 minima solutions and compare when they are the same (root finding) we can write everything and all to get an answer. How long does it take? Remember we can time this!  

Turns out we cannot just make it searching for all pts. Or at least not to this lecture course! What should we do?

We can indeed go back to the further optimization of our code, but look at the curve of the phase diagram, we might not need to make them very dense point! Maybe just a few points and use interpolation is enough. 

Given a data (1 variable 1 output) x,y if we can have a function that passes exactly on all such data points then it is an interpolation function. If we want to have a data in between any xi xi+1, just having f hat x would give us the interpolated value

<the follow are from older 374 Any data measured is given for discrete values.
• However, we need to know the values between
the discrete values. Thus, we may fit a curve to
such data to estimate values between discrete
points (interpolation).
• Or, even, using a curve fitted, we may try to
predict possible values outside of the discrete
values range. (extrapolation)>

<1. Interpolation and extrapolation schemes must model the
function between or beyond the known points, by some
plausible functional form.
2.The form should be sufficiently general so as to be able to
approximate large classes of functions which might arise in
practice.
3.By far most common among the functional forms used
are:
a. Polynomials (including linear functions)
b. Rational functions (quotients of polynomials) also turn
out to be extremely useful
c. Trigonometric functions
4. The number of points (minus one) used in an
interpolation scheme is called the order of the interpolation.>

Before any details we must know

1. Interpolation of points does not represent the exact solution! 
2. Interpolation using bad estimators (like high order polynomials) will make the interpolation wiggly!
3. Extrapolation should almost never be trusted. If you need, go to fitting

Interpolation can be done mainly in two ways
1. fitting using polynomial (n order for n+1 data points) eg lagrange or newton DDT 
2. piecewise polynomial (linear / quadratic / cubic / spline / etc

Although the most practical way we should say is still piecewise, we shall see first how to make them working (polynomial)

So what should the function f look like? We just know one thing, fxi = yi. Let’s see. If it is linear what can we know?

x1 x2 y1 y2 

y1 x-x2/x1-x2
y2 x-x1/x2-x1

We will call each this function L which satisfies the equation L(x1)=1 and L(x2)=1. 

The Lagrange polynomials use this idea. Basically if you have N+1 points you can have N polynomials to interpolate. In other way you can write fx = sum yi li for the N points. There is also a nice property about the Lagrange polynomial: that interpolating function is unique. 

Lagrange polynomials are easy to understand because the individual functions L just use data points and there is no need to calculate the coeffs.
But Lagrange polynomials may have some disadvantage:
1. Each polynomial function will be recalculated if new data points are added 

Another way of calculating the polynomials is the newton method (yes again!). Newtons method assumes the polynomials increases with the data size. So a +a1x-x1 blah blah. there is an interesting way of calculating the newtons method., (triangle way). Once the coefficients are determined, you could actually add more data! 

Newtons method adding one more data just calculates N times iteration. While for Lagrange you need N*n-1.

But, whatever the polynomial methods we use, let’s see how the functions behave when adding more orders? 

<explorative runges phenomenon, interactive demo>

Runges phenomenon basically says you’d be really careful if more orders are added, usually, they don’t help because too

## piece wise interpolation

<taken below from older mate374>

It is well well-known fact that problems can arise when a single
high-degree polynomial is fit to a large number of points.
• High-degree polynomials would obviously pass through all the
data points themselves, but they can oscillate wildly between
data points.
• When a large number of points is involved, a better interpolation
can be obtained using many low-order polynomials instead of a
single high-order polynomial.
• Each low-order polynomial is valid in one interval between two
or several points.
• In such cases, lower-degree polynomials can be fit to subsets of
the data points.
• If the lower-degree polynomials are independent of each other, a
piecewise approximation is obtained.
• This type of polynomial is called a spline function, or simply a
spline.
The name spline comes from the thin flexible rod, called a spline, used by draftsmen
to draw smooth curves through a series of discrete points.
• The spline is placed over the points and either weighted or pinned at each point. Due
to the flexure properties of a flexible rod, the slope and curvature of the rod are
continuous at each point. A smooth curve is then traced along the rod, yielding a
spline curve.
• Splines can be of any degree.
• Linear splines are simply straight line segments connecting each pair of data
points:
a. Linear splines are independent of each other from interval to interval.
b. Linear splines yield first-order approximating polynomials.
c. The slopes (i.e., first derivatives) and curvature (i.e., second derivatives) are
discontinuous at every data point.

<figure, what a spline and peg is>

A linear spline can be just viewed as a piece wise 1st order lagrange 

second order spline 

Quadratic splines yield second-order approximating polynomials.
• Quadratic splines have a continuous first derivative (slope) at the interior points (knots), and for n given
points, they require the solution of a linear system of 3n − 4 equations for the coefficients of the
polynomials.
• However, the second derivatives (curvatures) remain discontinuous.

For n given points there are n − 1 intervals, and using the standard form, the equation of the polynomial
in the ith interval, between points xi and xi +1, is given by:
fi (x) = ai x2 + bi x + ci for i = 1, 2, ..., n − 1

Overall, for n points there are n − 1 equations(splines), and since each equation has three
coefficients, a total of 3(n − 1) = 3n − 3 coefficients need to be determined.
The coefficients are determined by applying the following conditions:
1. Each polynomial fi (x) must pass through the endpoints of the interval, (xi , yi ) and (xi +1, yi +1),
which means that fi (xi ) = yi and fi (xi +1) = yi +1:
Since there are n − 1 intervals, these conditions give 2(n − 1) = 2n − 2 equations.
2. At the interior knots, the slopes (first derivative) of the polynomials from adjacent intervals
are equal. This means that as the curve that passes through an interior knot switches from
one polynomial to another, the slope is continuous. We use this important condition to write
additional equations. In general, the first derivative of the ith polynomial is:

A cubic spline yields a third-degree polynomial connecting each pair of data points.
• The slopes and curvatures of the cubic splines can be forced to be continuous at each data
point.
• In fact, these requirements are necessary to obtain the additional conditions required to
fit a cubic polynomial to two data points. Higher-degree splines can be defined in a similar
manner.
• Cubic splines have proven to be a good compromise between accuracy and complexity.
• For n given points there are n − 1 intervals, and using similar logic we used for quadratic
splines, the equation of the polynomial in the ith interval, between points xi and xi +1 is given
by:
fi (x) = ai x3 + bi x2 + ci x + di (8)
• Overall, there are n − 1 equations, and since each equation has four coefficients, a total of
4(n − 1) = 4n − 4 coefficients have to be determined.
• The coefficients are found by applying the following conditions:

1. Each polynomial fi (x) must pass through the endpoints of the interval, (xi , yi ) and (xi +1, yi +1),
which means that fi (xi ) = yi and fi (xi +1) = yi +1:
Since there are n − 1 intervals, this condition gives 2(n − 1) = 2n − 2 equations.
2. At the interior knots, the slopes (first derivatives) of the polynomials from the adjacent
intervals are equal. This means that as the curve that passes through an interior knot
switches from one polynomial to another, the slope must be continuous. The first derivative
of the ith polynomial is:
For n points the first interior point is i = 2, and the last is i = n − 1. Equating the first
derivatives at each interior point gives:
Since there are n − 2 interior points, this condition gives n − 2 additional equations.

3. At the interior knots, the second derivatives of the polynomials from adjacent intervals must
be equal. ⇒ This means that as the curve that passes through an interior knot switches
from one polynomial to another with continuous change of the slope (curvature).
• Thus, the second derivative of the polynomial in the ith interval is:
For n points, the first interior point is i = 2, and the last is i = n − 1. Equating the second
derivatives at each interior point gives:
6 ai—1 xi—1 + 2 bi—1 = 6 ai xi + 2 bi for i = 1, 2, ..., n − 1 (14)
Since there are n − 2 interior points, this condition gives n − 2 additional equations.
• Together, the three conditions give 4n − 6 equations. However, the n − 1 polynomials have
4n − 4 coeffici

The additional conditions are usually taken to be that the second derivative is zero at
the first point and at the last point. This gives two additional equations:
6 a1 x1 + 2 b1 = 0 and 6 an−1 xn + 2 bn−1 = 0
• Cubic splines with the second derivatives at the endpoints set equal to zero are
called natural cubic splines.
• Applying all the conditions gives a system of 4n − 4 linear equations for the 4n − 4
coefficients.

<for these examples we just show that what conditions should be met!  we dont let students to actually derive! >

<after all these, we should list how native interpolation solutions should be used. (yes we do now want to do matrix solving in this unit)>

<more important thing is, how do we show them the a b c coefficients should be determined. for a N point data curve, how large is the equation matrix?? later in the next unit, it will be a good entrypoint to introduce why we need systems of equations>

<a demo for python's interpolation using the splines, and how should we actually use them?>

<the demo definitely needs a discussion about the interpolation (supposedly most smooth curves, cubic spline are good enough), but what about extrapolation??>

<let's go back to the CO2 phase diagram situation, we can pick a few points in the P - T boundary curve, and decide how different interpolation works, are they even make sense? >

Before next class:

1) look back at the polynomial interpolation method. could you describe the runge's phenomenon in your own words?
2) we know extrapolation is typically not trusted, how about interpolation? what may interpolation help us achieving the true answer( now need to link to the optimization / root finding start points)
3) what if we do not want to pass all the points?
4) by solving the coefficients of the piecewise interpolation, we introduce the systems of equations. if we're not given the exact scipy implementation, how can we solve them in python / numpy?

<VERY VERY IMPORATNT: this lecture, is to make sure students know that interpolation itself, is some sort of root finding problem!>

