---
title: "L07 · Finding extrema in one dimension"
subtitle: "How are most stable material state determined? "
body-classes: lecture-page
---

## The question

**How can we numerical determine the minima and maxima points on a free energy surface to find the most stable phase?**

## Learning outcomes

<LLM, revise the learning outcome as needed>

## Opening question: from vdW EOS to phase diagram

In material science, for unary system (i.e. just 1 matter), a commonly asked question is: 

at certain pressure P and pressure T, what is the most stable matter state (i.e. solid, liquid, gas, etc)?

Our examples of vdW EOS from lectures 5 - 6 is perfect at demonstrating "what is a possible volume, at certain P and T". At certain pressure, you could find 2 physically meaningful roots (disregarding the middle). But are they stable? We will need to use the **Gibbs free energy** to ask that question.

Based on thermodynamics <just cite>, the gibbs free energy of a gas following vdW eos can be expressed as

<be careful of the statement, we do NOT want to do a normalization, should show the EXACT vdW EOS --> Gibbs, so that it is now per mole gibbs free energy>

G_per_mole = -RTln(V - b) - a /V + PV + C(T)

<foldable derivation provess
Acknoelwege that gibbs free energy = helmoltz + PV, and helmholtz A = int P dV
>

<now we can show a side-by-side shape between the vdW curve and the Gibbs curve, no demo yet, just plot>

What we are interested is that at this system, we can identify using the gibbs FE function (G(v) ), that the there are indeed 2 minima and 1 maxima of the function. the minima corresponds to the liquid / gas while 1 maxima is the transition state (unstable)

Numerically, what we ask are
1) find where the extrema are (V)
2) find what the extreme values are (G_liq, G_gas)
3) from the G_liq vs G_gas, we can now compare if in this condition, liqiid or gas is thermodynamically more stable!
4) naturally, if we collect so many such data, we construct a phase diagram (this is where the interpolation classes are about)
5) if we're even interesting in expressing the whole phase boundary, fitting them using polynomialas are possible (fitting class)

In this lecture we will deal with how to find the extremas

## The optimization problem

<following sentences are from the Kiusalass book excerpt, we will just make them a simple intro>

Extremas are defined at point on a continuous function, where at the value of the point f(x_e) is either smaller or larger than all surroundings (what about TS)
the idea of finding the extrema is often called the optimization. In practise, one often just need to consider the problem of finding the minima value of the function f(x). The optimization problem it self could be a very broad topic in both math, computer science and engineering, as it largely related to the design of a system. In this course, we would like to limit ourselves to the discussing of treating minimzation on 1D data to demonstrate the numerical.

<callout tip: minimization in very high dimension is key to the success of modern day AI systems, but they would be derived from the same principle taught in this lecture>

We will limit our discussion currently to the **unconstrained minimization**, such that only to find the stationary points (1st derivative of f(x) vanishes). Constrained optimization belongs to another big class of methods will be taught in other CHE / CME courses.

### Where do stationary points exist?

Mathamatically for a continuous and derivable function f(x) the 1st der f'(x) (df/dx) defines the stationary point. to distinguish the minimum and maximum points, we should use the second derivative f''

1. minumum: f' = 0; f'' > 0
2. maximum: f' = 0; f'' < 0

<callput tip: the instructor's trick is to relate the second der to the up / downwards of the curve. a convex curve has f'' larger and wanted to be dragged to 0 upwards. vice versa>


You would immediately realize, f' = 0 itself is another root finding problem! If we are able to get the f' evaluated (i.e. analytical solution, or direct finite method), just any method we learned in lecture 5 -6 could solve the minimization problem! 

In fact, indeed, bounded and unbounded methods would work with minimizaation

## Bounded methods for minimazation

Like bounded root finding, bounded minimization tries to searchfor the minimum between [a, b] (where the interval is h = b - a). 

the most well-known: The counterpart of bisection method in root finding will be the golden section search in minimization. 

Instead of the bisection method in root finding, where we add 1 intermediate point (at the center), we need actual 2 points 1 and 2 between each iteration.  In the golden section search, the 2 intervals are chosen as Rh from left and right where R = (1 + sqrt5)/2 (the golden ratio). we need to compare the 2 values f1 and f2 on each iteraction, if f1 > fx, the minima lives from x1 to the right end, vice versa

<folded region: why the golden ratio? use a figure to explain, could show kiusalass book analysis 

The golden section search is the counterpart of bisection used in finding roots of
equations. Suppose that the minimum of f (x) has been bracketed in the interval
(a , b) of length h. To telescope the interval, we evaluate the function at x1 = b− Rh
and x2 = a + Rh, as shown in Figure 10.2(a). The constant R is to be determined
shortly. If f1 > f2 as indicated in the figure, the minimum lies in (x1, b); otherwise
it is located in (a , x2).
Assuming that f1 > f2, we set a ← x1 and x1 ← x2, which yields a new interval
(a , b) of length h′
= Rh, as illustrated in Figure 10.2(b). To carry out the next tele-
scoping operation we evaluate the function at x2 = a + Rh′ and repeat the process.
The procedure works only if Figures 10.1(a) and (b) are similar (i.e., if the same
constant R locates x1 and x2 in both figures). Referring to Figure 10.2(a), we note that
x2− x1 = 2Rh− h. The same distance in Figure 10.2(b) is x1− a = h′
− Rh′. Equating
the two, we get
2Rh− h= h′
− Rh′
f(x)
2Rh− h
f1 f2
Rh
Rh
a
x1 x2
h
(a)
b x
Figure 10.2. Golden section telescoping.
f(x)
Rh'
Rh'
a b
x1 x2
h'
x
(b)
: 19593 0521985820/705132.85252
378 Introduction to Optimization
Substituting h′
= Rh and canceling h yields
2R− 1= R(1− R)
the solution of which is the golden ratio.
1
R=−1 + √5
2= 0.618 033 989. . . (10.3)
Note that each telescoping decreases the interval containing the minimum by
the factor R, which is not as good as the factor is 0.5 in bisection. However, the golden
search method achieves this reduction with one function evaluation, whereas two
evaluations would be needed in bisection.

>

The golden section search method works similarly as the bisection, that the interval reduced by 1/R each time. so the steps to get the minima is ...

<how do we confirm the minima is within the bound?>

## Open domain method: newton minimization

We would just use newton-raphson to minimize the function f, by finding the f'=0, this would simply indicate that in the newton's method, we update the initial by

\(x_{k+1}=x_k-\frac{f'(x_k)}{f''(x_k)},\)

conceptually this is not hard to estimate at all, but the basic question is whether or not we can find (reasonablly the f' and f'')

<callout caution: many problems, especially high dimensional, are not easy to estimate the first or even secondary derivative (called jacobian and hessian matrices), newton's method need a log modification, so that there a series of gradient-based and gradient free methods in high dimensional optimization>

<what about the newton in 1D from scipy?>

in fact, because we don't always know / aware of how the 1/f'' behave (especially for really unaccessible data), we sometimes just want to make a simple move scaled with the f', so that x_k+1 = x_k - alpha f'

This is the **gradient descent** method presented in 1D. The behaviour of course, depends on how fast can we get the minimum (too big step --> fail, too small step --> slow). 

<callout info: actually, controlling how large a minimization step is universal problem in both material simulation optim (minimimze structure energy), in AI/machine learning (lowering the learning loss)>

## Hands on from the vdW Gibbs

choose the bracket or open domain method, see how many steps we need  to get to the minima?

More material question: do we know which state is more thermodynamically favirable?

if one state is slightly higher than the other, how do we know its stable or metastable? (barrier)

<yt vide embed for co2 liquefication https://www.youtube.com/watch?v=M2duzKxb1QM>

### Do we always have 2 phases minima?

When you increase the value of the T_c, you would see that there is just 1 minima, moving Pressure just got the minima change for a very large range (I think it's the critical pressure point, )

<there is a very good example https://marimo.app/l/horuvv I asked another agent to create, BUT! it's using reduced parameters, I don't want students to get lost, let's use CO2 directly>

<what determines / how to find Tc?>

### From minimization to phase diagram

If we have worked out how to make the minimization finding, we can actually combine the numerical with root finding to ask

which P, gives G(liq) - G(air) = 0, where G_liq and G_air are the 2 minima found? 

this pressure is called saturation pressure, where liq and gas co-exist. this corresponds to the phase diagram chart we see! 

<eventually the co2 phase diagram, where now from we can use the wigglystuff library puck example to put the chart to solve the gibbs free energy>

<we don't need to say how to get the actual phase diagram for exp co2, just the liquid-gas-supercritical from these 3 lectures>

## Summary of root finding and minimization

## Before next lecture

We don't need to go 1 million T / P points to point the phase boundary. what if we just have a few lines and make them smooth? This is the interpolation








